name: NextJS CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Navigate to Go Component Directory
        run: cd path/to/your/nextjs/component
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint --ext .js,.jsx,.ts,.tsx .
        continue-on-error: false

      - name: Unit Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Dockerimage to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./nextjs/
          file: ./nextjs/Dockerfile
          push: true
          tags: Dockerhub_username/my-app_JS:latest,Dockerhub_username/my-app_JS:any_tag
