name: Wordpress CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr, phpcs
      - name: Install Composer Dependencies
        run: composer install --prefer-dist
      - name: Run Tests
        run: composer run-phpunit
      - name: Run phpcs
        run: phpcs -q --report=checkstyle src | cs2pr
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Dockerimage to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./wordpress/
          file: ./wordpress/Dockerfile
          push: true
          tags: Dockerhub_username/my-app_Wordpress:latest,Dockerhub_username/my-app_Wordpress:any_tag
